//import { VideoProject } from "@/types/videos";

// export const allVideoProjects: VideoProject[] = [
//   //Long Form Videos
//   {
//     id: "rVVeLdouViU",
//     video_title: "Storytelling Ai Videos",
//     video_description: "",
//     tags: ["Resume Tips", "FAANG Career", "Job Preparation", "Career Advice"],
//     cover_image: "long1",
//     publish_date: "2024-08-04",
//     client_name: "Stack Learner",
//     client_image: "/companies/sl-logo.png",
//     client_feedback: "",
//     video_link: "https://www.youtube.com/watch?v=hOOQbjngys4&list=PL6AUZXkTxww5L5QsBaBuOObGnCWyfEXoe&index=1",
//     project_images: [],
//     category: ["StoryTelling"],
//     duration: "4:41",
//     software_used: ["DaVinci Resolve"],
//   },
//   {
//     id: "JSZmQxg3fos",
//     video_title: "IAS KAVACH ( Coach Up IAS Institute ) ADs",
//     video_description:
//       "This workshop helps application developers explore DSA through real-world problems, connecting data structures to business challenges and fostering a problem-solving mindset for practical solutions.",
//     tags: ["DSA", "Developer Skills", "Problem Solving", "Career Prep"],
//     cover_image: "long2",
//     publish_date: "2024-04-08",
//     client_name: "Stack Learner",
//     client_image: "/companies/sl-logo.png",
//     client_feedback: "",
//     video_link: "https://www.youtube.com/watch?v=WvLw8WodrD0&list=PL6AUZXkTxww5L5QsBaBuOObGnCWyfEXoe&index=2",
//     project_images: [],
//     category: ["Coorporate Video"],
//     duration: "2.41",
//     software_used: ["Davinci Resolve", "After Effects"],
//   },
//   {
//     id: "ufRtWGd0cXq",
//     video_title:
//       "News Editing",
//     video_description: `Discover the powerful HeartMath technique to calm your nervous system in just 60 seconds! This quick and effective method can help reduce anxiety, stress, and feelings of overwhelm, promoting a sense of relaxation and calmness.`,
//     tags: ["Stress Relief", "Mental Health", "Wellness", "HeartMath"],
//     cover_image: "long3",
//     publish_date: "2025-06-06",
//     client_name: "Growthleo",
//     client_image: "/companies/growthleo.png",
//     client_feedback: "",
//     video_link: "https://www.youtube.com/watch?v=Zvp56gA3YPE&list=PL6AUZXkTxww5L5QsBaBuOObGnCWyfEXoe&index=3",
//     project_images: [],
//     category: ["News", "Documentary"],
//     duration: "4:25",
//     software_used: ["Davinci Resolve"],
//   },
//   {
//     id: "ufRtWGd0cXo",
//     video_title:
//       "Storytelling Ai Videos - Part 2",
//     video_description: `Discover the powerful HeartMath technique to calm your nervous system in just 60 seconds! This quick and effective method can help reduce anxiety, stress, and feelings of overwhelm, promoting a sense of relaxation and calmness.`,
//     tags: ["Stress Relief", "Mental Health", "Wellness", "HeartMath"],
//     cover_image: "long4",
//     publish_date: "2025-06-06",
//     client_name: "Growthleo",
//     client_image: "/companies/growthleo.png",
//     client_feedback: "",
//     video_link: "https://www.youtube.com/watch?v=J0HZNXW8iC8&list=PL6AUZXkTxww5L5QsBaBuOObGnCWyfEXoe&index=1",
//     project_images: [],
//     category: ["StoryTelling"],
//     duration: "4:25",
//     software_used: ["Davinci Resolve"],
//   },
//     {
//     id: "ufRtWGd0cXw",
//     video_title:
//       "Corporate Profile & promotional Video (career infinity institute)",
//     video_description: `Discover the powerful HeartMath technique to calm your nervous system in just 60 seconds! This quick and effective method can help reduce anxiety, stress, and feelings of overwhelm, promoting a sense of relaxation and calmness.`,
//     tags: ["Stress Relief", "Mental Health", "Wellness", "HeartMath"],
//     cover_image: "long5",
//     publish_date: "2025-06-06",
//     client_name: "Growthleo",
//     client_image: "/companies/growthleo.png",
//     client_feedback: "",
//     video_link: "https://www.youtube.com/watch?v=dk4gWFKOiRg&list=PL6AUZXkTxww5L5QsBaBuOObGnCWyfEXoe&index=5",
//     project_images: [],
//     category: ["Coorporate Video"],
//     duration: "4:25",
//     software_used: ["Davinci Resolve"],
//   },
//   //..........................................
//   //Reels
//   {
//     id: "7OuSRaIPOds",
//     video_title:
//       "Ranjana Singh Rathore (NDTV Anchor)",
//     video_description: `You've tried every habit hack, diet, and self-help book—but real change still feels impossible. Why? Because you're trying to change your behavior without changing your identity.`,
//     tags: ["Personal Growth", "Habits", "Mindset", "Self-Improvement"],
//     cover_image: "shorts16",
//     publish_date: "2025-06-20",
//     client_name: "Growthleo",
//     client_image: "/companies/growthleo.png",
//     client_feedback: "",
//     video_link: "https://www.youtube.com/watch?v=yjEZSQMRFEQ&list=PL6AUZXkTxww5GR3gKIGPaZ8epqVuA0s_-",
//     project_images: [],
//     category: ["Reels", "Shorts"],
//     duration: "1:03",
//     software_used: ["Davinci Resolve"],
//   },
//   {
//     id: "esjJzKjx9Fo",
//     video_title: "Shorts",
//     video_description: `Feeling stuck, lost, or like your best years are behind you? You're not alone and you're not too late.`,
//     tags: ["Mental Health", "Brain Training", "Transformation", "Wellness"],
//     cover_image: "shorts18",
//     publish_date: "2025-07-11",
//     client_name: "Growthleo",
//     client_image: "/companies/growthleo.png",
//     client_feedback: "",
//     video_link: "https://www.youtube.com/watch?v=Vd4fpOydIXk&list=PL6AUZXkTxww5GR3gKIGPaZ8epqVuA0s_-&index=2",
//     project_images: [],
//     category: ["Shorts"],
//     duration: "1:01",
//     software_used: ["Davinci Resolve"],
//   },
//   {
//     id: "Qwwgg_qt5ew",
//     video_title: "Ranjana Singh Rathore (NDTV Anchor)",
//     video_description:
//       "Apply logic to simplify your conditional problems. Watch the video to understand how!",
//     tags: ["Coding Tips", "Conditional Logic", "Problem Solving", "Shorts"],
//     cover_image: "shorts17",
//     publish_date: "2024-01-16",
//     client_name: "Stack Learner",
//     client_image: "/companies/sl-logo.png",
//     client_feedback: "",
//     video_link: "https://www.youtube.com/watch?v=BikSMTGGRiw&list=PL6AUZXkTxww5GR3gKIGPaZ8epqVuA0s_-&index=3",
//     project_images: [],
//     category: ["Reels", "Shorts"],
//     duration: "0:49",
//     software_used: ["After Effects"],
//   },
//   {
//     id: "TiZvFO99rpw",
//     video_title: "Ranjana Singh Rathore (NDTV Anchor)",
//     video_description:
//       "Every time you visit a website, your browser sends an HTTP request, and the server responds. But how does this process actually work?",
//     tags: ["HTTP", "Web Basics", "Networking", "Shorts"],
//     cover_image: "shorts19",
//     publish_date: "2025-02-27",
//     client_name: "Stack Learner",
//     client_image: "/companies/sl-logo.png",
//     client_feedback: "",
//     video_link: "https://www.youtube.com/watch?v=3rRLUbr_EaQ&list=PL6AUZXkTxww5GR3gKIGPaZ8epqVuA0s_-&index=4",
//     project_images: [],
//     category: ["Reels", "Shorts"],
//     duration: "0:31",
//     software_used: ["After Effects"],
//   },
//   {
//     id: "2esQF01ob78",
//     video_title: "Ranjana Singh Rathore (NDTV Anchor)",
//     video_description:
//       "Every time you use an app or website, APIs are working behind the scenes to fetch data. But what exactly is an API, and how do API endpoints work? 🤔 Watch this video to learn with simple examples!",
//     tags: ["API", "Web Basics", "Backend", "Shorts"],
//     cover_image: "shorts20",
//     publish_date: "2025-03-05",
//     client_name: "Stack Learner",
//     client_image: "/companies/sl-logo.png",
//     client_feedback: "",
//     video_link: "https://www.youtube.com/watch?v=3zHU0WQtl7s&list=PL6AUZXkTxww5GR3gKIGPaZ8epqVuA0s_-&index=5",
//     project_images: [],
//     category: ["Reels", "Shorts"],
//     duration: "0:57",
//     software_used: ["After Effects"],
//   },
//   {
//     id: "fH24XyxcfOc",
//     video_title: "Ranjana Singh Rathore (NDTV Anchor)",
//     video_description:
//       "",
//     tags: ["API", "Granola", "Ecofaming", "Shorts"],
//     cover_image: "shorts21",
//     publish_date: "2025-03-06",
//     client_name: "Eco Farming",
//     client_image: "/companies/Ecofarming.png",
//     client_feedback: "",
//     video_link: "https://www.youtube.com/watch?v=e1Rz3irvI5c&list=PL6AUZXkTxww5GR3gKIGPaZ8epqVuA0s_-&index=6",
//     project_images: [],
//     category: ["Reels", "Shorts", "Promo"],
//     duration: "0:55",
//     software_used: ["Davinci Resolve", "After Effects"],
//   },
// ];


import { VideoProject } from "@/types/videos";

export const allVideoProjects: VideoProject[] = [
  // Long Form Videos
  {
    id: "rVVeLdouViU",
    video_title: "Storytelling Ai Videos",
    cover_image: "long1",
    video_link: "https://www.youtube.com/watch?v=hOOQbjngys4",
    category: ["StoryTelling"],
    duration: "4:41",
  },
  {
    id: "JSZmQxg3fos",
    video_title: "IAS KAVACH (Coach Up IAS Institute) ADs",
    cover_image: "long2",
    video_link: "https://www.youtube.com/watch?v=WvLw8WodrD0",
    category: ["Corporate Video"],
    duration: "2:41",
  },
  {
    id: "ufRtWGd0cXq",
    video_title: "News Editing",
    cover_image: "long3",
    video_link: "https://www.youtube.com/watch?v=Zvp56gA3YPE",
    category: ["News", "Documentary"],
    duration: "4:25",
  },
  {
    id: "ufRtWGd0cXo",
    video_title: "Storytelling Ai Videos - Part 2",
    cover_image: "long4",
    video_link: "https://www.youtube.com/watch?v=J0HZNXW8iC8",
    category: ["StoryTelling"],
    duration: "4:25",
  },
  {
    id: "ufRtWGd0cXw",
    video_title:
      "Corporate Profile & Promotional Video (Career Infinity Institute)",
    cover_image: "long5",
    video_link: "https://www.youtube.com/watch?v=dk4gWFKOiRg",
    category: ["Corporate Video"],
    duration: "4:25",
  },

  // Reels / Shorts
  {
    id: "7OuSRaIPOds",
    video_title: "Ranjana Singh Rathore (NDTV Anchor)",
    cover_image: "shorts16",
    video_link: "https://www.youtube.com/watch?v=yjEZSQMRFEQ",
    category: ["Reels", "Shorts"],
    duration: "1:03",
  },
  {
    id: "esjJzKjx9Fo",
    video_title: "Shorts",
    cover_image: "shorts18",
    video_link: "https://www.youtube.com/watch?v=Vd4fpOydIXk",
    category: ["Shorts"],
    duration: "1:01",
  },
  {
    id: "Qwwgg_qt5ew",
    video_title: "Ranjana Singh Rathore (NDTV Anchor)",
    cover_image: "shorts17",
    video_link: "https://www.youtube.com/watch?v=BikSMTGGRiw",
    category: ["Reels", "Shorts"],
    duration: "0:49",
  },
  {
    id: "TiZvFO99rpw",
    video_title: "Ranjana Singh Rathore (NDTV Anchor)",
    cover_image: "shorts19",
    video_link: "https://www.youtube.com/watch?v=3rRLUbr_EaQ",
    category: ["Reels", "Shorts"],
    duration: "0:31",
  },
  {
    id: "2esQF01ob78",
    video_title: "Ranjana Singh Rathore (NDTV Anchor)",
    cover_image: "shorts20",
    video_link: "https://www.youtube.com/watch?v=3zHU0WQtl7s",
    category: ["Reels", "Shorts"],
    duration: "0:57",
  },
  {
    id: "fH24XyxcfOc",
    video_title: "Ranjana Singh Rathore (NDTV Anchor)",
    cover_image: "shorts21",
    video_link: "https://www.youtube.com/watch?v=e1Rz3irvI5c",
    category: ["Reels", "Shorts", "Promo"],
    duration: "0:55",
  },
];